events {}

http {
    server {
          listen 443 ssl;

          ssl_certificate /etc/nginx/certs/fullchain.crt;
          ssl_certificate_key /etc/nginx/certs/server.key;

          location / {
              root /usr/share/nginx/html;
              index index.html;
          }
    }
}

